// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ1ulNN0Euc00U3U3WJ1ElQHreHTrw7YU',
    appId: '1:855757580374:web:011c658ee05737900673f7',
    messagingSenderId: '855757580374',
    projectId: 'chattingapp-6652e',
    authDomain: 'chattingapp-6652e.firebaseapp.com',
    storageBucket: 'chattingapp-6652e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrDDZsOpOf0vu9edGu3JV27YOvCuUFSWs',
    appId: '1:855757580374:android:4a47b01d452ad4650673f7',
    messagingSenderId: '855757580374',
    projectId: 'chattingapp-6652e',
    storageBucket: 'chattingapp-6652e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuuyvBzQcDyzcHsJrQ8jA06LqEyY0G8Eo',
    appId: '1:855757580374:ios:d1295509e6454f650673f7',
    messagingSenderId: '855757580374',
    projectId: 'chattingapp-6652e',
    storageBucket: 'chattingapp-6652e.appspot.com',
    iosBundleId: 'com.example.chattingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuuyvBzQcDyzcHsJrQ8jA06LqEyY0G8Eo',
    appId: '1:855757580374:ios:d1295509e6454f650673f7',
    messagingSenderId: '855757580374',
    projectId: 'chattingapp-6652e',
    storageBucket: 'chattingapp-6652e.appspot.com',
    iosBundleId: 'com.example.chattingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ1ulNN0Euc00U3U3WJ1ElQHreHTrw7YU',
    appId: '1:855757580374:web:9141d6f305919fa90673f7',
    messagingSenderId: '855757580374',
    projectId: 'chattingapp-6652e',
    authDomain: 'chattingapp-6652e.firebaseapp.com',
    storageBucket: 'chattingapp-6652e.appspot.com',
  );
}
