name: Flutter Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v4

      # 2. Set up Flutter environment
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # 원하는 Flutter 버전을 지정하세요

      # 3. Set up JDK for Android
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 4. Get Flutter dependencies
      - name: Flutter Pub Get
        run: flutter pub get

      # 5. Build the APK (debug and release)
      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Build APK (Release)
        run: flutter build apk --release

      # 6. Upload the Debug APK as artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      # 7. Upload the Release APK as artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
